enableInlineBuilds: true

enableInlineHunks: true

nodeLinker: node-modules

npmRegistryServer: "${REGISTRY_URL:-https://registry.npmmirror.com}"

npmScopes:
  lilconfig:
    npmRegistryServer: "${REGISTRY_URL:-https://registry.npmjs.org}"

unsafeHttpWhitelist:
  - "*.npmmirror.com"
