name: Build apps CI (Intel)

on:
  push:
    branches:
      - 'build/v**'

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          VERSION=${{ github.ref }}
          VERSION=${VERSION#refs/heads/build/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - run: npm run install:ci

      - run: npm run install:babel

      - run: npm run build:ci

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          draft: true
          prerelease: true
          files: |
            build/linux/qqtools-${{ env.VERSION }}-linux64.zip
            build/mac/qqtools-${{ env.VERSION }}-mac.zip
            build/win/qqtools-${{ env.VERSION }}-win64.zip
            build/win32/qqtools-${{ env.VERSION }}-win32.zip